version: '3'
services:
  db:
    container_name: orm-spikes-db
    image: 'postgres:14'
    volumes:
      - './.data/db:/var/lib/postgresql/data'
    restart: 'always'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: orm-spikes_dev
      TZ: 'Etc/UTC'